spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: SA
    password: 
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprodNamingStrategy
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /console   